var arreglos = ["perro", "gato", "loro"];
console.log(arreglos[0], arreglos[1], arreglos[2], arreglos.length);
var animals = [
    "perro",
    "gato",
    "ratón",
    "elefante",
    "león",
    "tigre",
    "zorro",
    "lobo",
    "mono",
    "gallo",
    "serpiente",
    "gallina",
    "pájaro",
    "pato",
    "aguila",
    "búho",
    "halcón",
    "tucán",
    "flamenco",
    "pelícano",
    "avestruz",
    "cisne",
    "buey",
    "vaca",
    "cabra",
    "oveja",
    "cerdo",
    "jabalí",
    "carnero",
    "cordero",
    "burro",
    "asno",
    "mula",
    "caballo",
    "yegua",
    "zebra",
    "camello",
    "dromedario",
    "bisonte",
    "rinoceronte",
    "hipopótamo",
    "elefante marino",
    "ballena",
    "delfín",
    "foca",
    "leopardo",
    "jaguar",
    "pantera",
    "puma",
    "leopardo de las nieves",
    "oso polar",
    "oso pardo",
    "oso negro",
    "urso panda",
    "koala",
    "kangaroo",
    "wallaby",
    "canguro",
    "opossum",
    "mapache",
    "zarigüeya",
    "liebre",
    "conejo",
    "marmota",
    "ardilla",
    "hámster",
    "cobayo",
    "gerbil",
    "hurón",
    "faisán",
    "pato cuchara",
    "pato mandarín",
    "pato real",
    "cisne negro",
    "cisne científico",
    "cernícalo",
    "palomo",
    "colibrí",
    "cuervo",
    "graja",
    "pájaro carpintero",
    "carpintero rojo",
    "pájaro carpintero pico de plata",
    "pájaro carpintero de Lewis",
    "pájaro carpintero de pico corto",
    "pájaro carpintero de pico largo",
    "carpintero azul",
    "pájaro carpintero de pico fino",
    "pájaro carpintero de pico grueso",
    "pájaro carpintero de pico ancho",
    "pájaro carpintero de pico curvo",
    "pájaro carpintero de pico recto"];
var i = 0;
while(i < animals.length) {
    console.log(animals[i]);
    i++;
}
    